fastlane_version "2.129.0"

default_platform :ios

platform :ios do

  name = "EmojiKit"
  main_branch = "main"

  desc "Create a new version"
  lane :version do |options|
    sh("cd .. && bash scripts/validate_git.sh " + main_branch)
    sh("cd .. && bash scripts/validate_project.sh")
    sh("cd .. && bash scripts/build.sh " + name)
    sh("cd .. && bash scripts/test.sh " + name)

    type = options[:type]
    version = version_bump_podspec(path: 'Version', bump_type: type)
    git_commit(path: "*", message: "Bump to #{version}")
    add_git_tag(tag: version)
    push_git_tags()
    push_to_git_remote()
  end

end
